<?php
/**
 * Agent Weekly Settlement History Panel
 */
require_once __DIR__ . '/header.php';

$admin_id = $_SESSION['user_id'];

try {
    $count_stmt = $pdo->prepare("SELECT COUNT(*) FROM weekly_settlements WHERE agent_id = ?");
    $count_stmt->execute([$admin_id]);
    $total_records = intval($count_stmt->fetchColumn());

    $limit = 10;
    $page = isset($_GET['page']) ? max(1, intval($_GET['page'])) : 1;
    $offset = ($page - 1) * $limit;
    $total_pages = ceil($total_records / $limit);

    $stmt = $pdo->prepare("
        SELECT * 
        FROM weekly_settlements 
        WHERE agent_id = ? 
        ORDER BY week_end DESC
        LIMIT " . intval($limit) . " OFFSET " . intval($offset) . "
    ");
    $stmt->execute([$admin_id]);
    $settlements = $stmt->fetchAll();
} catch (PDOException $e) {
    $settlements = [];
    $total_records = 0;
    $total_pages = 0;
    $page = 1;
    $offset = 0;
    $limit = 10;
}
?>

<div class="glass-card p-4">
    <div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3">
        <div>
            <h5 class="text-white fw-bold mb-1"><i class="fa-solid fa-wallet text-indigo me-2"></i>Payout Settlement Log</h5>
            <span class="text-secondary small">Weekly commission payout logs from the Super Admin</span>
        </div>
        <div>
            <a href="<?= BASE_URL ?>/generate_report.php?type=settlement" target="_blank" class="btn btn-primary-gradient"><i class="fa-solid fa-file-pdf me-2"></i>Export PDF Report</a>
        </div>
    </div>

    <?php if (count($settlements) === 0): ?>
        <div class="text-center py-5 text-secondary small">
            <i class="fa-solid fa-receipt mb-3 d-block" style="font-size: 3rem; color: #475569;"></i>
            No payout settlement records found. Weekly logs are generated by the Super Admin at the end of each week.
        </div>
    <?php else: ?>
        <div class="table-responsive">
            <table class="table table-swift table-dark table-hover table-borderless align-middle datatable-swift">
                <thead>
                    <tr>
                        <th>Cycle Period</th>
                        <th>Total Gross Sales</th>
                        <th>Payable Commission (2%)</th>
                        <th>Net Earnings Kept</th>
                        <th>Payout Status</th>
                        <th>Processed Date</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($settlements as $s): 
                        $net_earning = floatval($s['total_sales']) - floatval($s['commission_payable']);
                    ?>
                        <tr>
                            <td>
                                <span class="fw-semibold text-white d-block">Week Cycle</span>
                                <span class="text-secondary small font-monospace"><?= date('d M Y', strtotime($s['week_start'])) ?> to <?= date('d M Y', strtotime($s['week_end'])) ?></span>
                            </td>
                            <td>₹<?= number_format($s['total_sales'], 2) ?></td>
                            <td class="text-warning fw-semibold">₹<?= number_format($s['commission_payable'], 2) ?></td>
                            <td class="text-success fw-bold">₹<?= number_format($net_earning, 2) ?></td>
                            <td>
                                <?php if ($s['status'] === 'paid'): ?>
                                    <span class="badge bg-success bg-opacity-10 text-success border border-success border-opacity-25 px-2 py-1">RECEIVED / PAID</span>
                                <?php else: ?>
                                    <span class="badge bg-warning bg-opacity-10 text-warning border border-warning border-opacity-25 px-2 py-1">PENDING CLEARANCE</span>
                                <?php endif; ?>
                            </td>
                            <td class="text-secondary small">
                                <?= !empty($s['marked_paid_at']) ? date('d M Y H:i', strtotime($s['marked_paid_at'])) : '--' ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        
        <?php if ($total_pages > 1): ?>
            <div class="d-flex justify-content-between align-items-center mt-4">
                <div class="text-secondary small">
                    Showing <?= $offset + 1 ?> to <?= min($total_records, $offset + $limit) ?> of <?= $total_records ?> entries
                </div>
                <nav aria-label="Page navigation">
                    <ul class="pagination pagination-swift mb-0">
                        <li class="page-item <?= ($page <= 1) ? 'disabled' : '' ?>">
                            <a class="page-link" href="?<?= http_build_query(array_merge($_GET, ['page' => $page - 1])) ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php for ($p = 1; $p <= $total_pages; $p++): ?>
                            <li class="page-item <?= ($p == $page) ? 'active' : '' ?>">
                                <a class="page-link" href="?<?= http_build_query(array_merge($_GET, ['page' => $p])) ?>"><?= $p ?></a>
                            </li>
                        <?php endfor; ?>
                        <li class="page-item <?= ($page >= $total_pages) ? 'disabled' : '' ?>">
                            <a class="page-link" href="?<?= http_build_query(array_merge($_GET, ['page' => $page + 1])) ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>

<?php
require_once __DIR__ . '/footer.php';
?>
